# Generated by Django 5.0.2 on 2025-03-25 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_update_categories'),
        ('events', '0005_mediacategory_media_category'),
    ]

    operations = [
    ]
