# Generated by Django 5.0.2 on 2025-04-13 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_update_media_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediacategory',
            name='name',
            field=models.CharField(choices=[('rangoli', 'Rangoli'), ('mehendi', 'Mehendi'), ('tshirt_painting', 'T-Shirt Painting'), ('face_painting', 'Face Painting'), ('nail_art', 'Nail Art'), ('dance', 'Dance'), ('singing', 'Singing'), ('fashion_show', 'Fashion Show'), ('instrument_playing', 'Instrument Playing'), ('cooking_without_fire', 'Cooking Without Fire'), ('treasure_hunt', 'Treasure Hunt'), ('glam_up', 'Glam Up'), ('prize_distribution', 'Prize Distribution'), ('group_alike_day', 'Group-Alike Day'), ('bollywood_day', 'Bollywood Day'), ('indo_western_day', 'Indo-Western Day')], max_length=100, unique=True),
        ),
    ]
